version: 2

jobs:
  ubuntu-clang:
    docker:
      - image: ubuntu:18.10
    environment:
      CC: /root/project/clang_7.0.1/bin/clang
      CXX: /root/project/clang_7.0.1/bin/clang++
      LD: /root/project/clang_7.0.1/bin/ld.lld
      LD_LIBRARY_PATH: /root/project/clang_7.0.1/lib
    steps:
      - checkout
      - run: apt update || true; apt update && apt install -y make cmake libtinfo5 xz-utils curl
      - run:
          name: Install LLVM
          command: |
            curl -SL http://releases.llvm.org/7.0.1/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz \
              | tar -xJC . && \
              mv clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04 clang_7.0.1 && pwd && ls
      - run:
          name: Build
          command: cmake -DCMAKE_CXX_FLAGS="-stdlib=libc++ -fuse-ld=$LD" . && make
      - run:
          name: Verify binary is built
          command: ./botc --help

workflows:
  version: 2
  build:
    jobs:
      - ubuntu-clang
