version: 2

jobs:
  ubuntu-clang:
    docker:
      - image: ubuntu:19.10
    environment:
      LD: /usr/bin/ld
    steps:
      - checkout
      - run: apt update || true; apt update
      - run:
          name: Install packages required for CircleCI
          command: apt install -y ssh tar gzip ca-certificates 
      - restore_cache:
          keys:
            - apt-v1-
      - run:
          name: Configure CLang repository
          command: |
            apt install -y gnupg software-properties-common
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
            add-apt-repository "deb http://apt.llvm.org/eoan/ llvm-toolchain-eoan-9 main"
      - run:
          name: Install CLang and test deps
          # update cache ver when changing list here:
          command: apt install -y make cmake clang-9 lldb-9 lld-9 clang-9 libc++-9-dev libc++abi-9-dev curl
      - run:
          name: Cleanup cache
          command: |
            cd /var/cache/apt/archives/
            for pkg in `ls *.deb | cut -d _ -f 1 | sort -u`; do
              if [ $(ls $pkg\_* | wc -l) -gt 1 ]; then
                files=$(ls -vr $pkg\_*)
                rmfiles=`echo $files | cut -d " " -f 2-`
                rm -v $rmfiles
              fi
            done
      - save_cache:
          key: apt-v1-{{ .Revision }}
          paths:
            - "/var/cache/apt"
      - run:
          name: Configure build environment
          command: |
            update-alternatives --install /usr/bin/cc cc /usr/bin/clang-9 60
            update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-9 60
            update-alternatives --install /usr/bin/ld ld /usr/bin/ld.lld-9 60
      - run:
          name: Build
          command: cmake -DCMAKE_CXX_FLAGS="-stdlib=libc++ -fuse-ld=$LD" . && make
      - run:
          name: Verify binary is built
          command: ./botc --help
      - run:
          name: Sanity check
          command: |
            curl https://bitbucket.org/Torr_Samaho/zandronum/raw/ZA_3.0/wadsrc/static/crashbot.lump -LO && \
            curl https://bitbucket.org/Torr_Samaho/zandronum/raw/ZA_3.0/wadsrc/static/dfultbot.lump -LO && \
            curl https://bitbucket.org/Torr_Samaho/zandronum/raw/ZA_3.0/wadsrc/static/fatbot.lump -LO && \
            curl https://bitbucket.org/Torr_Samaho/zandronum/raw/ZA_3.0/wadsrc/static/humanbot.lump -LO && \
            curl https://bitbucket.org/Torr_Samaho/zandronum/raw/ZA_3.0/wadsrc/static/sausgbot.lump -LO && \
            curl https://github.com/TarCV/debotc/raw/0.3.0/debotc_defs.bts -LO && \
            curl https://github.com/TarCV/debotc/releases/download/0.3.0/debotc.kexe -LO && \
            chmod +x debotc.kexe && \
            for LUMP in *.lump; do \
            ./debotc.kexe $LUMP > $LUMP.0.botc && \
            ./botc $LUMP.0.botc $LUMP.1.lump && \
            ./debotc.kexe $LUMP.1.lump > $LUMP.1.botc && \
            ./botc $LUMP.1.botc $LUMP.2.lump && \
            ./debotc.kexe $LUMP.2.lump > $LUMP.2.botc && \
            diff $LUMP.1.botc $LUMP.2.botc; \
            done
      - run:
          name: Prepare for possible publishing
          command: |
            mkdir -p output.bin || true
            mv botc output.bin
      - persist_to_workspace:
          root: .
          paths:
            - output.bin

workflows:
  version: 2
  build:
    jobs:
      - ubuntu-clang
